export * from './api-path.util';
export * from './auth-ms/endpoints';
export * from './programs-ms/endpoints';
export * from './calendar-ms/endpoints';
export * from './facilities-ms/endpoints';
export * from './teaching-ms/endpoints';
export * from './enrollments-ms/endpoints';
export * from './assessments-ms/endpoints';
export * from './gateway/endpoints';
